server:
  port: 8096
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
pring:

spring:
  application:
    name: lagou-service-autodeliver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
     show-details: ALWAYS
lagou-service-resume:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 15000

    #对所有操作请求都进行重试
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 0 #重试次数
    MaxAutoRetriesNextServer: 0 #切换实例的重试次数
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载均衡策略
